### ISSUE TITLE
Not able to use it

### ISSUE THREAD

**Issue by dharamgoyal** [tgpfeiffer/restful-openerp#18]
I am new in odoo and want to use REST API for all module please explain me how can i use that

**Comment by tgpfeiffer** [comment]
First of all, the last version that I personally have used this with is OpenERP 6.1. I don't know if it still works with recent versions of Odoo.

As for the installation, the process is described in the Readme: https://github.com/tgpfeiffer/restful-openerp#installation

The way this tool works is that you can list, get, modify and create all object types (e.g. `product.product`) in Odoo via an HTTP call to restful-openerp. The Readme describes how to perform the list, get, and create operations in the [Status section](https://github.com/tgpfeiffer/restful-openerp#status). Please let me know if you have any more specific questions.

**Comment by dharamgoyal** [comment]
Using latest odoo version 9.0 i have done all process which mention as in https://github.com/tgpfeiffer/restful-openerp#installation and run http://odoo.47billion.com/xmlrpc from REST client tool but getting 404 page not found error.

**Comment by tgpfeiffer** [comment]
Your `restful-openerp.cfg` file should contain a line like

    url: http://odoo.47billion.com:8069/xmlrpc/

and then, when you start `restfulOpenErpProxy.py` you should be able to access `http://localhost:8068/<dbname>/product.product` (where `dbname` is the name of a database in your installation) – note the different port and hostname! – with any valid username and password. I don't know your database name, but I am able to connect to your XML-RPC endpoint using the above config line.

**Comment by dharamgoyal** [comment]
okay so here product.product is table name right?

**Comment by tgpfeiffer** [comment]
It's not exactly the "table name", but "model name". However, as far as I know there is a 1:1 relation to tables, so it's more or less the same.

**Comment by dharamgoyal** [comment]
ubuntu@ODOO:/opt/odoo/addons/restful-openerp-master$ python restfulOpenErpProxy.py
2016-09-23 10:06:53+0000 [-] Log opened.
2016-09-23 10:06:53+0000 [-] Server starting up with backend: http://localhost/xmlrpc/
2016-09-23 10:06:53+0000 [-] Site starting on 8068
2016-09-23 10:06:53+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f711c63bcb0>

Not able to access this http://localhost:8068/odoodb/product.product
on browser getting Unable to connect


please can you help why it's happening i have try many times also i want response in json, so is it possible?

**Comment by dharamgoyal** [comment]
@tgpfeiffer tgpfeiffer Realy appreciate with your response, please let me know where i am doing mistake, i hope for your response.

**Comment by tgpfeiffer** [comment]
In general there are three machines involved: a) the machine running Odoo, b) the machine running restful-openerp and c) the machine with your browser.

Judging from your message, in your case all three machines are identical, is this correct? Otherwise, please write 1) the address of *a* into the `restful-openerp.cfg` file on *b* and 2) connect to *b* with your browser on port 8068. For me, when I add your instance `http://odoo.47billion.com/xmlrpc/` to my configuration file, then I can access it fine via restful-openerp (except that user/password is wrong, for obvious reasons).

If you see nothing after the "Starting factory ..." line in the log, then something is wrong with the way you access restful-openerp, otherwise please paste these log lines here.
